export const RETRIEVE_POSTS_SUCCESS = 'RETRIEVE_POST_SUCCESS';
export const RETRIEVE_POSTS_ERROR = 'RETRIEVE_POST_ERROR';

export const RETRIEVE_SINGLE_POST_SUCCESS = 'RETRIEVE_SINGLE_POST_SUCCESS';
export const RETRIEVE_SINGLE_POSTS_ERROR = 'RETRIEVE_SINGLE_POST_ERROR';

export const UPDATE_SINGLE_POST_SUCCESS = 'UPDATE_SINGLE_POST_SUCCESS';
export const UPDATE_SINGLE_POST_ERROR = 'UPDATE_SINGLE_POST_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';


export const UNAUTHORIZED_USER = 'UNAUTHORIZED_USER';
