export const RETRIEVE_POSTS_SUCCESS = 'RETRIEVE_POST_SUCCESS';
export const RETRIEVE_POSTS_ERROR = 'RETRIEVE_POST_ERROR';


export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';